//SIGN IN
export const SIGN_IN_INPROGRESS = 'SIGN_IN_PROGRESS';
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_IN_FAILURE = 'SIGN_IN_FAILURE';

//SIGN OUT
export const SIGN_OUT_INPROGRESS = 'SIGN_OUT_INPROGRESS';
export const SIGN_OUT_SUCCESS = 'SIGN_OUT_SUCCESS';
export const SIGN_OUT_FAILURE = 'SIGN_OUT_FAILURE';

//SIGN UP
export const SIGN_UP_INPROGRESS = 'SIGN_UP_INPROGRESS';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_UP_FAILURE = 'SIGN_UP_FAILURE';
